<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Personal\Module'                        => __DIR__ . '/Module.php',
    'Personal\Controller\IndexController' => __DIR__ . '/src/Personal/Controller/IndexController.php',
    'PersonalTest\Framework\TestCase'        => __DIR__ . '/tests/Personal/Framework/TestCase.php',
    'PersonalTest\SampleTest'                => __DIR__ . '/tests/Personal/SampleTest.php',
);
