<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Com\Module'                        => __DIR__ . '/Module.php',
    'Com\Controller\IndexController' => __DIR__ . '/src/Com/Controller/IndexController.php',
    'ComTest\Framework\TestCase'        => __DIR__ . '/tests/Com/Framework/TestCase.php',
    'ComTest\SampleTest'                => __DIR__ . '/tests/Com/SampleTest.php',
);
