<script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?
        key=AIzaSyCvHsufo7Ee0GxE-nX6suLDIIhLWEsZAAQ
        &sensor=true&libraries=drawing">
</script>
 
<script type="text/javascript">
 	
        //Variables globales utilizadas
	var lat = null;
	var lng = null;
	var map = null;
	var mapOptions = null;
	var geocoder = new google.maps.Geocoder();
	var latLng = null;
	var marker = null;
	
	jQuery(document).ready(function(){
        //obtenemos los valores en caso de tenerlos en un formulario ya guardado en la base de datos
            lat = jQuery('#lat').val();
            lng = jQuery('#lng').val();
     
	 //Asignamos al evento click del boton la funcion codeAddress
            jQuery('#localizar').click(function(){
                codeAddress();
                return false;
                });
	 
	 //Asignamos la funci贸n change a la lista de c谩maras
	 jQuery('#lista_camaras').change(function(){
		 var string = jQuery('#lista_camaras').val().split(',');
		 latLng = new google.maps.LatLng(string[0],string[1]);	
		 updatePositionCam(latLng);
		 return false;
	 });
     
	 //Inicializamos la funci贸n de google maps una vez el DOM este cargado
            google.maps.event.addDomListener(window, 'load', initialize);
                });
	
	
	
    function initialize() {
		
		if(lat !='' && lng != '')
      		{
				lat = jQyery('#lat').val();
				lng = jQuery('#lng').val();				
      	   		latLng = new google.maps.LatLng(lat,lng);
				alert(latLng); 
     	 }
     	 else
     	 {
     	   //Si no creamos el objeto con una latitud por defecto.
		   	 lat = -34.54320745035504;
			 lng = -58.712049599227896;
    	     latLng = new google.maps.LatLng(lat,lng);
			 updatePosition(latLng);
     	 }
		
        mapOptions = {
          center: latLng,
          zoom: 15,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
		
        map = new google.maps.Map(document.getElementById("maps"), mapOptions);
			
		/*var drawingManager = new google.maps.drawing.DrawingManager({
			drawingMode: google.maps.drawing.OverlayType.MARKER,
			drawingControl: true,
			drawingControlOptions: {
			  position: google.maps.ControlPosition.TOP_CENTER,
			  drawingModes: [
				google.maps.drawing.OverlayType.MARKER,
				google.maps.drawing.OverlayType.CIRCLE,
				google.maps.drawing.OverlayType.POLYGON,
				google.maps.drawing.OverlayType.POLYLINE,
				google.maps.drawing.OverlayType.RECTANGLE
			  ]
    },
   		 	markerOptions: {
			  icon: 'http://localhost/zend2/public/img/cad/police.CAD.violence.stalking.png',
			  title: document.title
			},
			circleOptions: {
		  fillColor: '#ffff00',
		  fillOpacity: 1,
		  strokeWeight: 5,
		  clickable: false,
		  editable: true,
		  zIndex: 1
		}
  });
  	 	drawingManager.setMap(map); */
  
  		marker = new google.maps.Marker({
            map: map,//el mapa creado en el paso anterior
            position: latLng,//objeto con latitud y longitud
            draggable: true //que el marcador se pueda arrastrar
        });
		
		//Cargo la capa de camaras  	
        var geoLayer = new google.maps.KmlLayer({ url: 'http://www.enexti.com/site/zend2/public/xml/camaras.kmz'});
                geoLayer.setMap(map);
		map.setZoom(15);
		map.setCenter(latLng);		
		google.maps.event.addListener(marker, 'dragend', function(){
                updatePosition(marker.getPosition());
            });
	  }
	  
	
          function codeAddress() {
  			var address = document.getElementById('direccion').value +  "San Miguel, Buenos Aires, Argentina, AR";
			geocoder = new google.maps.Geocoder();
			
		  	geocoder.geocode(
                                {
                                    'address': address,
                                },  function(results,status) {
                                    if(status == "OK")
                                        {
                                          jQuery('#direccion').val (results[0].formatted_address);
										  map.setCenter(results[0].geometry.location);
										  map.setZoom(15);
										  marker.setPosition(results[0].geometry.location);
										  jQuery('#lat').val(results[0].geometry.location.lat());
										  jQuery('#lng').val(results[0].geometry.location.lng());
										  //updatePosition(results[0].geometry.location);
										 
                                        }
                                        else {
											alert("No se encontr贸 direcci贸n");
											return "nada";}
                                });
 	}

          //funcion que simplemente actualiza los campos del formulario Direcci贸n y LatLng 
          function updatePosition(Point)
              {
                       jQuery('#lat').val(Point.lat());
                       jQuery('#lng').val(Point.lng());
                       lat = jQuery('#lat').val();
                            lng = jQuery('#lng').val();
                       geocoder.geocode(
                                    {
                                        latLng: Point,
                                    },  function(results,status) {
                                        if(status == "OK")
                                            {
                                              jQuery('#direccion').val (results[0].formatted_address);						  
                                            }
                                            else { return "nada";}
                                    });
              } 

          //Funci贸n para facilitar la posici贸n de una c谩mara
          function updatePositionCam(Point)
          {
		  
		   jQuery('#lat').val(Point.lat());
		   jQuery('#lng').val(Point.lng());
		   lat = jQuery('#lat').val();
		   lng = jQuery('#lng').val();
		   geocoder.geocode(
                                {
                                    latLng: Point,
                                },  function(results,status) {
                                    if(status == "OK")
                                        {
                                          jQuery('#direccion').val (results[0].formatted_address);
										  map.setCenter(results[0].geometry.location);
										  map.setZoom(16);
										  marker.setPosition(results[0].geometry.location);
										  
                                        }
                                        else {
											alert("nada");
											return "nada";
											}
                                });
	  } 
	   
	
    </script>

 <div id="maps" style="width:100%;height:400px;"></div>
 
 <form id="google" name="google">
    <table>
    	<tr>
            <td>
                <label>C醡ara</label>
            </td>
            <td>            
                <select name="camara" id="lista_camaras">
                    <option value="-34.539847000771,-58.7095142357342">CD001 - R. Balb韓 y Mu駉z</option>
                    <option value="-34.5413792962741,-58.71127608844842">CF002 - R. Balb韓 y Paunero</option>
                    <option value="-34.54231594040719,-58.71202965056572">CD003 - R. Balb韓 y Av. Per髇</option>
                </select>  
            </td>
        </tr>
        <tr>
            <td>
                <label>Direcci髇</label>
            </td>
            <td>
                <input name="direccion" type="text" id="direccion" value="" size="80" />
            </td>
            <td>
                <input type="text" name="lat" id="lat" value="" />
                <input type="text" name="lng" id="lng" value="" />
            </td>
        </tr>
        <tr>
            <td valign="top"></td>
            <td valign="top">
                <button id="localizar" class="btn btn-success">Localizar</button> 
                <button id="crear_evento" class="btn btn-success">Crear</button> 
            </td>
        </tr>
    </table>        
    <!--campos ocultos donde guardamos los datos-->
    
 </form>   


